CREATE TABLE clientes (
  id VARCHAR(36) PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  empresa VARCHAR(100) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE campanhas (
  id VARCHAR(36) PRIMARY KEY,
  cliente_id VARCHAR(36) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);

CREATE TABLE videos (
  id VARCHAR(36) PRIMARY KEY,
  campanha_id VARCHAR(36) NOT NULL,
  titulo VARCHAR(100) NOT NULL,
  url_destino TEXT NOT NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (campanha_id) REFERENCES campanhas(id) ON DELETE CASCADE
);

CREATE TABLE cliques (
  id INT AUTO_INCREMENT PRIMARY KEY,
  video_id VARCHAR(36) NOT NULL,
  rede_social VARCHAR(50) NOT NULL,
  ip VARCHAR(45) NOT NULL,
  data_hora DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
);

CREATE TABLE redes_sociais (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(20) NOT NULL,
 );

CREATE TABLE curtos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_curto VARCHAR(10) NOT NULL UNIQUE,
  id_cliente VARCHAR(36) NOT NULL,
  id_campanha VARCHAR(36) NOT NULL,
  id_video VARCHAR(36) NOT NULL,
  id_rede VARCHAR(20) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

